

@startuml
interface BaseStream {}

interface Stream extends BaseStream {}

interface IntStream extends BaseStream {}

interface LongStream extends BaseStream {}

interface DoubleStream extends BaseStream {}
@enduml